### PR TITLE
Updated tests, they all pass now

### PR DESCRIPTION
**Pull request by wsdookadr**
The slurp and spurt functions imported from Mojo::Util no longer exist. Their place was taken by the new methods of the Mojo::File package: Mojo::File::slurp and Mojo::File::spurt.

This patch brings the tests up-to-date.

When run with the following command, they all pass:

    TEST_HYPNOTOAD=1 TEST_HYPNOTOAD_PATH=$(which hypnotoad) prove -v -Ilib t/

This was tested with [Mojolicious 8.42](https://metacpan.org/pod/release/SRI/Mojolicious-8.42/lib/Mojolicious.pm) . The Perl version dependency was upgraded to `>= 5.16` (for further details please see the [commit message here](https://github.com/augensalat/mojolicious-plugin-sizelimit/pull/5/commits/d6a0415b1d123937f49fe1c03e161b1885960e81) ).

This also addresses [the test failures on CPAN](https://www.cpantesters.org/distro/M/Mojolicious-Plugin-SizeLimit.html?oncpan=1&distmat=1&version=0.005&grade=3) for the current version.

The following oneliner was written regarding the minimal version of Mojolicious required in order for the tests to pass, after merging this pull request:

    mkdir test_results; pushd . && cd ~/myprojects/mojo && MOJO_VERSIONS=$(git tag | sed 's/^v//' | perl -ne 'print if $_ >= 6.54') && popd ; for mv in ${MOJO_VERSIONS[@]}; do echo $mv ; pm-uninstall -f Mojolicious; cpanm -n -q Mojolicious@$mv;  prove -v -Ilib t/ > test_results/$mv.txt 2>&1 ;  done

(this oneliner assumes you have the [App::pmuninstall](https://metacpan.org/pod/App::pmuninstall) module installed)

The first (earliest) version of Mojolicious on which the tests here will PASS is 8.02

### CODE REVIEW

**Review by augensalat — CHANGES_REQUESTED** [review]
Hi Stefan,
thanks a lot for your contribution.
Two questions:
- Why did you bump the Mojolicious requirement to 8.02? `Mojo::Util::(slurp|spurt)` was deprecated in 7.15 and I don't see any Changes in 8.02 that touch this area. If there is not a real reason, please change this value to 7.15.
- Why did you bump the Perl requirement to 5.16? I noticed that sri did the same thing for Mojolicious a few days ago, but this module should stay compatible with older versions of Mojolicious and Perl as long as possible. Please lower the Perl requirement back to 5.010001 if there is no reason for 5.16.

**Comment by wsdookadr** [comment]
Hey Bernhard,

> Why did you bump the Mojolicious requirement to 8.02

I've [run the tests against all versions of Mojolicious](https://github.com/augensalat/mojolicious-plugin-sizelimit/pull/5/commits/a84aeadefbaec02485146afed318c5b497a3305a) and 8.02 turned out to be the earliest where these tests are passing.

> and I don't see any Changes in 8.02 that touch this area

Yeah, I was expecting the change to be mentioned in the Changelog, but I didn't find it, so [I just did exhaustive testing instead](https://github.com/augensalat/mojolicious-plugin-sizelimit/pull/5/commits/a84aeadefbaec02485146afed318c5b497a3305a).

> Why did you bump the Perl requirement to 5.16 [..] Please lower the Perl requirement back to 5.010001

[I just tried this in this commit](https://github.com/augensalat/mojolicious-plugin-sizelimit/pull/5/commits/7633598dad19ca5f216d337cba2c9a3971fe564b), and also adapted .travis.yml accordingly, [it's failing on the older versions: 5.10,5.12,5.14](https://travis-ci.org/github/augensalat/mojolicious-plugin-sizelimit/builds/692056749). What seems unusual is that it's trying to pull Mojolicious `8.50` even though the Makefile.PL tells it to pull `8.02`.

**Review by augensalat — CHANGES_REQUESTED** [review]
No, we can't do that, just because the tests by default load the most current Mojolicious version which requires 5.16.
I will have a look at the problem later or in the next days.

**Comment by wsdookadr** [comment]
I see. So I've read further, and I realized a [cpanfile](https://metacpan.org/pod/distribution/Module-CPANfile/lib/cpanfile.pod) [was missing](http://blogs.perl.org/users/neilb/2017/05/specifying-dependencies-for-your-cpan-distribution.html). It seems to be required in order for `cpanm` to know which versions of dependencies we want installed.

[I got `5.14` to build as well](https://travis-ci.org/github/augensalat/mojolicious-plugin-sizelimit/builds/692074247). What I'm noticing now is the following:

[source](https://travis-ci.org/github/augensalat/mojolicious-plugin-sizelimit/jobs/692074258#L172)
```
$ perlbrew use 5.10
ERROR: The installation "5.10" is unknown.
```

[source](https://travis-ci.org/github/augensalat/mojolicious-plugin-sizelimit/jobs/692074257#L172)
```
$perlbrew use 5.12
ERROR: The installation "5.12" is unknown.
```

So Travis-CI doesn't support 5.10 or 5.12 anymore. So that's the reason why the tests break there, because perlbrew is trying to switch to versions of Perl that don't exist on the Travis-CI build machines.

Now, I see that as a limitation of Travis-CI, but still, I think when uploading to CPAN, there will be enough versions and environments there to cover 5.10 and 5.12

**Comment by wsdookadr** [comment]
> No, we can't do that, just because the tests by default load the most current Mojolicious version which requires 5.16.

@augensalat Ok, I did the following:
* lowered the required version of Mojolicious to 7.31 for older Perl versions
* lowered the minimum required version of Perl to 5.10.1
* added support for the missing perlbrew versions 5.10,5.12,5.14

[Some tests are failing](https://travis-ci.org/github/augensalat/mojolicious-plugin-sizelimit/builds/692109338) on old Perls for Mojolicious 7.31

Switching back to 8.02 like I mentioned initially, [and the tests are passing on every single version of Perl, including the old ones](https://travis-ci.org/github/augensalat/mojolicious-plugin-sizelimit/builds/692110650).

**Comment by wsdookadr** [comment]
> I will have a look at the problem later or in the next days.

Hi @augensalat 

Is anything else needed here? Can I help you with anything for this pull request to get merged?

**Comment by wsdookadr** [comment]
Closing due to maintainer being unresponsive

**Pull request closed without merging**
